### ISSUE TITLE
New `usrmerge` issues.

### ISSUE THREAD

**Issue by jcrodriguez1989** [rocker-org/rocker#554] opened 2024-07-09 20:30 UTC
Hello, thanks for your wonderful work at rocker 🙌
I am having some more `usrmerge` issues (I saw there are related issues already closed).

This simple Dockerfile is failing:
```sh
FROM rocker/r-base:4.2.0
RUN apt-get update && apt-get -y install \
    libcurl4-openssl-dev
```
with error:
```sh
Preparing to unpack .../libc6_2.38-13_amd64.deb ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Checking for services that may need to be restarted...
Checking init scripts...

The current installation does not have a merged-/usr layout.
This is unsupported and unpacking libc6 would break the system.
Refusing to unpack. Please install the usrmerge package and try again.

dpkg: error processing archive /var/cache/apt/archives/libc6_2.38-13_amd64.deb (--unpack):
 new libc6:amd64 package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/libc6_2.38-13_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Is there any easy workaround? Or should I just go to `rocker/r-base:latest` (I am trying to avoid this)?

**Comment by eddelbuettel** [comment] 2024-07-10 04:54
Why do you use 4.2.0?  The `usrmerge` happened later (as far as I remember) and _current_ container files build.

**Comment by jcrodriguez1989** [comment] 2024-07-10 11:54
We use 4.2.0 just because that's the R version we use for dev.
There's no easy workaround? If not, we can try switching to a newer R version.

**Comment by eitsupi** [comment] 2024-07-10 12:06
IMO, r-base supports only the latest R version and is not a suitable image for applications that stop at older R versions.
I recommend to use rocker/r-ver or use rig to install any version of R.

**Comment by eddelbuettel** [comment] 2024-07-10 12:13
@jcrodriguez1989 You are facing a self-created dilemma I cannot resolve for you:
- you desire the newest kernel and distribution features (which we *do* offer in rocker/r-base)
- you also desire a two-years outdated R which CRAN and us *do not* support _in the current versions_

So *you* need to think through what you _really_ want:
- For R 4.2.0 (if you really need it) `docker pul rocker/r-base:4.2.0 to r-rocker/r-base:4.2.3 are always available.  They are point-in-time frozen _by design_ so you get R 4.2.* as it was when everything was current.
- For current Linux you get R 4.4.1 along with it. Just use rocker/r-base (ie latest).  If you _really_ need R 4.2.3 you can still (easily) compile it from source on the container.

As the request is fundamentally mismatched with what we do here (and, possibly, based on a misunderstanding) I will close this.

**Closed by eddelbuettel** 2024-07-10 12:13 UTC

**Comment by jcrodriguez1989** [comment] 2024-07-10 12:18
I will opt for the `rocker/r-ver` alternative.
Thank you both very much for your help.
