### ISSUE TITLE
r-base 3.1.2

### ISSUE THREAD

**Issue by dougmet** [rocker-org/rocker#144] opened 2015-10-14 10:18 UTC
I know this has been discussed with issue #114 but I didn't fully understand the conclusion. If you do:

```
docker pull r-base:3.1.2
```

and then

```
docker run -it rbase:3.1.2 R --version
```

You get 
```
R version 3.1.3 RC (2015-03-06 r67947) -- "Smooth Sidewalk"
```

Instead of 3.1.2 as you would expect. Can I confirm there is a reason it is not possible to match the R version to the tag?

**Comment by cboettig** [comment] 2015-10-15 17:18
@dougmet Yeah, sorry about that. The docker container pulls whatever it gets from the debian:testing repos, so once those updated, 3.1.2 updated as well.  

Future tags shouldn't do this (I think), because the version number is now explicit in the `apt-get` line.  

Nevertheless, because our image builds R from the Debian binaries rather than from source (but see rocker/r-devel for the latter), the r-base images will probably never be well suited for running older R versions.  That is, you couldn't come back and run the Dockerfile for 3.2.2 a few years later and get R 3.2.2, because apt-get simply wont be able to find that version on the debian:testing repos in a few years, which will have moved on.  

Most other official Docker images do this a bit differently from us: they fix a particular Debian release (e.g. Jessie), and then build the focal application from source.  By fixing the Debian release it is less likely that the binaries needed to build the fixed version from source will change sometime in the future.  And by building from source means they are not restricted to the binary version (of R or whatever the focal application is) that ships in that Debian release (e.g. Jessie) which is almost always behind whatever is current.  This approach means that most official Dockerfiles with specific version tags will continue to build the version you expect (and thus continue to benefit from security patches to the OS) even after they are far from current, though I suppose it's not guaranteed. (@eddelbuettel knows far more about the details of Debian and can correct me)

Because Dirk already does the hard work of building the R binaries that go into debian:testing, our approach just re-uses those binaries in order that r-base:latest really does build the latest R without duplicating that effort on the Dockerfile end.  Providing an up-to-date dockerized version of R and avoiding unnecessary maintenance time are really the main goals of the rocker image, we're not really focused on providing outdated images (even though we know some people would like to be able to reproduce old bugs that have since been fixed).

Hope that made some sense, sorry to ramble on.

**Comment by eddelbuettel** [comment] 2015-10-15 17:30
Nicely put, Carl.   

Just to add:   we were balancing the ability to get _current_ R versions easily and reliably.  Users typically want the R that is current.  Debian can stall (when preparing a release), ditto for Ubuntu.  So we go with Debian testing (and occassional unstable for selected packages) -- rather than hard-pinning-down-of-existing versions.  We find the former more important.   So if you need a particular version, you may have to build those from tarballs.

With that, I'd like to close the issue.  It is more-or-less 'by design'.

**Comment by dougmet** [comment] 2015-10-15 17:58
Many thanks @cboettig and @eddelbuettel for the very clear explanation. I was indeed interested from a reproducibility point of view but, as you say, building on old boxes is not a problem. I was just being lazy! Thanks for the great project.

**Closed** 2015-10-15 17:58 UTC

**Comment by eddelbuettel** [comment] 2015-10-15 18:22
I do wonder if there was a simple enough setup we could try to support that ... but I don't have a good solution yet either.
