### ISSUE TITLE
Trouble Installing Package ("tm")

### ISSUE THREAD

**Issue by WilliamFrecker** [rocker-org/rocker#223] opened 2017-03-21 15:15 UTC
Forgive me if this is a user issue, but I'm trying to setup a rocker container for a class I'm taking and I've been unable to get the dependencies for SocialMediaLab installed, specifically the text mining package tm. I've pasted my console below

`

> install.packages("tm")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/tm_0.7-1.tar.gz'
Content type 'unknown' length 526702 bytes (514 KB)
==================================================
downloaded 514 KB

* installing *source* package ‘tm’ ...
** package ‘tm’ successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/local/lib/R/include -DNDEBUG  -I/usr/local/include -I"/usr/local/lib/R/site-library/BH/include" -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
gcc -std=gnu99 -I/usr/local/lib/R/include -DNDEBUG  -I/usr/local/include -I"/usr/local/lib/R/site-library/BH/include" -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c copy.c -o copy.o
gcc -std=gnu99 -I/usr/local/lib/R/include -DNDEBUG  -I/usr/local/include -I"/usr/local/lib/R/site-library/BH/include" -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
g++ -I/usr/local/lib/R/include -DNDEBUG  -I/usr/local/include -I"/usr/local/lib/R/site-library/BH/include" -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c tdm.cpp -o tdm.o
tdm.cpp: In function ‘Rcpp::List tdm(Rcpp::StringVector, bool, std::vector<std::basic_string<char> >, std::vector<std::basic_string<char> >, unsigned int, unsigned int, unsigned int, unsigned int)’:
tdm.cpp:26:9: error: ‘boost’ has not been declared
         boost::tokenizer<> tok(s);
         ^
tdm.cpp:26:26: error: expected primary-expression before ‘>’ token
         boost::tokenizer<> tok(s);
                          ^
tdm.cpp:26:33: error: ‘tok’ was not declared in this scope
         boost::tokenizer<> tok(s);
                                 ^
tdm.cpp:29:14: error: ‘boost’ has not been declared
         for (boost::tokenizer<>::iterator it = tok.begin();
              ^
tdm.cpp:29:31: error: expected primary-expression before ‘>’ token
         for (boost::tokenizer<>::iterator it = tok.begin();
                               ^
tdm.cpp:29:32: error: ‘::iterator’ has not been declared
         for (boost::tokenizer<>::iterator it = tok.begin();
                                ^
tdm.cpp:29:32: note: suggested alternatives:
In file included from /usr/include/c++/4.9/bits/stl_algobase.h:65:0,
                 from /usr/include/c++/4.9/tr1/unordered_map:35,
                 from /usr/local/lib/R/site-library/Rcpp/include/Rcpp/platform/compiler.h:172,
                 from /usr/local/lib/R/site-library/Rcpp/include/Rcpp/r/headers.h:48,
                 from /usr/local/lib/R/site-library/Rcpp/include/RcppCommon.h:29,
                 from /usr/local/lib/R/site-library/Rcpp/include/Rcpp.h:27,
                 from tdm.cpp:3:
/usr/include/c++/4.9/bits/stl_iterator_base_types.h:118:12: note:   ‘std::iterator’
     struct iterator
            ^
/usr/include/c++/4.9/bits/stl_iterator_base_types.h:118:12: note:   ‘std::iterator’
tdm.cpp:30:14: error: ‘it’ was not declared in this scope
              it != tok.end();
              ^
/usr/local/lib/R/etc/Makeconf:141: recipe for target 'tdm.o' failed
make: *** [tdm.o] Error 1
ERROR: compilation failed for package ‘tm’
* removing ‘/usr/local/lib/R/site-library/tm’
Warning in install.packages :
  installation of package ‘tm’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp42Prap/downloaded_packages’
>

`

**Comment by WilliamFrecker** [comment] 2017-03-21 15:23
FWIW: I've been able to install SocialMediaLab with all dependencies from my Windows machine running RStudio without any issues.

**Comment by eddelbuettel** [comment] 2017-03-21 15:32
The comparison to Windows is irrelevant as that gets you _binary_ packages.  Here you install from source, and I have _no idea_ why it is failing.

I fairly regularly check Rcpp against all its reverse dependencies -- tm included -- and have not seen this.  I also won't have time to debug this for you so I suggest to down to the basics and try it one package (of its dependencies) at a time.

**Comment by cboettig** [comment] 2017-03-21 17:42
@WilliamFrecker not sure what rocker image you're using but I cannot replicate the error,`install.packages("tm")` runs just fine on the current rocker images I tested e.g. (`rocker/rstudio` and `r-base`).  Please see CONTRIBUTING.md for information we need when you file bug reports.  Since this doesn't look like a bug on our end I'll close this out here.  Good luck.

**Closed by cboettig** 2017-03-21 17:42 UTC

**Comment by WilliamFrecker** [comment] 2017-03-21 19:03
For posterity, it was an issue with permissions. 

> By default, the RStudio user does not have access to root, such that users cannot install binary libraries with apt-get without first entering the container (see docker exec as described below). To enable root from within RStudio, launch the container with the flag -e ROOT=TRUE, e.g.

source: https://github.com/rocker-org/rocker/wiki/Using-the-RStudio-image

**Comment by cboettig** [comment] 2017-03-21 19:09
@WilliamFrecker Thanks, but you should not need root for `install.packages()` to work with the `rocker/rstudio` image.  please ensure you are using the current version of `rocker/rstudio`

**Comment by WilliamFrecker** [comment] 2017-03-21 19:28
I'm a student, and I am admittedly new with a lot of this. I apologize if I'm not using the correct terms in my descriptions. I know that I could install packages (ie. install.packages("twitteR")), but I couldn't install the package tm (see above ). Installing a fresh version of Rocker made no difference, but when I installed rocker with the root flag I was able to successfully run install.packages("tm") without any issues.

This probably isn't the place for my issues and I had apologized from the start if it was a user issue. Thanks for taking the time to respond regardless. Is there a proper forum for user issues?

**Comment by cboettig** [comment] 2017-03-21 19:35
@WilliamFrecker No worries, we don't really have a great forum; though you'll find some rocker-related issues and knowledgeable people on stackoverflow.  Didn't mean to be discouraging, just only so much we can do from here.  Could be something to do with how you are linking local volumes or have configured your user, or something that you've changed on the image.  If I run: 

```bash
docker pull rocker/rstudio
docker run --rm -p 8787:8787 rocker/rstudio
```

I can `install.packages("tm")` without error.  Usually these things are pretty reproducible in docker so I'm surprised I can't replicate your error.  Anyway, best of luck, sounds like you have a work-around at very least.

**Comment by eddelbuettel** [comment] 2017-03-21 19:35
"Normally" a Docker container places you straight into root.  You can install right away.

The RStudio container is a little different.   You still have really answered Carl's basic quesiton (ie: "which container") -- "Rocker" is the name for the collection, and as Carl stated in r-base they install just fine.  I also worked in two other containers today without issues.  

In any event, we're all busy so there is not point to navel gaze this to death.
