### ISSUE TITLE
Migrating from Dockerhub?

### ISSUE THREAD

**Issue by guidopetri** [rocker-org/rocker#521] opened 2023-03-16 14:56 UTC
As per [this blog post](https://blog.alexellis.io/docker-is-deleting-open-source-images/), it seems like Dockerhub is going to start deleting the images for every organization that has been created that is not on a paid plan, starting ~30 days from now.

While I appreciate this is probably too early to ask - are there any plans for the Rocker images to move to a different container registry? Or is Rocker already on a paid team plan, and this wouldn't affect the images up on Dockerhub?

**Comment by eddelbuettel** [comment] 2023-03-16 14:58
Duplicate of https://github.com/rocker-org/rocker-versioned2/issues/615

**Closed by eddelbuettel** 2023-03-16 14:58 UTC

**Comment by guidopetri** [comment] 2023-03-16 15:02
Ah thanks, I had not seen that. Sorry for the duplicate

**Comment by eddelbuettel** [comment] 2023-03-16 15:06
We know -- It is really hard as we have 'too many repos' in the org and triaging helps, but also "hides" issues.
