### ISSUE TITLE
Please support MAJOR and MAJOR.MINOR version tags

### ISSUE THREAD

**Issue by bsolomon1124** [rocker-org/rocker#398] opened 2020-05-05 15:15 UTC
[Other languages](https://hub.docker.com/_/python?tab=description) commonly support multiple aliases that 'waterfall' down to the PATCH version:

```
3.8.2-buster, 3.8-buster, 3-buster, buster
```

This allows me to `docker pull python:3.8-buster` being assured that it's the latest PATCH version for that MAJOR.MINOR version.

r-base currently does not follow this common practice and it makes tracking version updates a pain.

Specying `r-base:4.0.0` leaves me required to manually check for PATCH version updates in downstream code.

**Comment by eddelbuettel** [comment] 2020-05-05 15:28
This is a very loaded and complicated topic.  You may be are aware but Rocker provides _two complete and mostly non-overlapping_ approaches to this.  See [our RJournal paper](https://journal.r-project.org/archive/2017/RJ-2017-065/index.html) for more.  The r-ver stack does try to help with the 'waterfall' versions.

Now,  `rocker/r-base:3.6.3` and `rocker/r-base:4.0.0` are about as specific as you can get here as they describe the _two most recent R releases by the version numbers used upstream_.  And I like being explicit.  Now, creating extra tags at the hub.docker.com layer is (mostly manual) work that I am not particularly interested in or have time for as this project is just one of several projects I contribute to as a volunteer (and an unpaid one at that).   But identifying versions this way is easy, there are other repos with the base information (if memory serves one of r-lib or rhub or ... has just that, and there is probably as a rest interface behind it).

**Comment by bsolomon1124** [comment] 2020-05-05 16:02
@eddelbuettel 

> You may be are aware but Rocker provides two complete and mostly non-overlapping approaches to this.

I am not familiar with this paper; thanks for linking.  However, reading through the "Versioned" section there, I am not quite sure I see how that satisfies the common desire to pin to a MINOR version and let PATCH float.  (One example of this is in CI/CD pipelines.)  I do however see how there would be an added layer of difficulty because of the upstream/downstream factor here that is not present in places such as the Python images that I linked to.

> Now, creating extra tags at the hub.docker.com layer is (mostly manual) work that I am not particularly interested in or have time for as this project is just one of several projects I contribute to as a volunteer (and an unpaid one at that).

First, thank you 😄 for helping to make these images available in the first place.  The only thing I would note here is that (again using Python as an example), the process of this "waterfall tagging" is [mostly done in an automated way](https://github.com/docker-library/python/blob/master/update.sh).  (With Python, even the Dockerfiles themselves are built automatically off [templates](https://github.com/docker-library/python/blob/master/Dockerfile-alpine.template), basically using an `itertools.product()`-like matrix of versions and base images.

**Comment by cboettig** [comment] 2020-05-06 21:04
@bsolomon1124 Thanks, we've had other requests to have more floating tags as well.  As Dirk mentioned already, Rocker Project has a separate 'versioned' stack at https://github.com/rocker-org/rocker-versioned, and we're just about to launch https://github.com/rocker-org/rocker-versioned2 for R 4.0.0 going forward that uses a similarly automated system for generating Dockerfiles.   

Feedback on these efforts would be greatly appreciated, (probably in there respective issue trackers is best).  In particular, note there's a lot of potential moving parts since it is not just the R version and the linux distro version a user might want to keep track of (in particular, we currently have tags to denote CUDA version, since for ML/GPU applications matching libraries to hardware is critical).  All of these versions could also 'waterfall' as you describe, but I am a bit nervous about the subsequent proliferation of tags.  


Also just a note that the desired automation could probably be done just as easily elsewhere in a CI/CD pipeline using the current infrastructure.  (e.g. a CI script using `r-base` could merely do precisely the same logic as in those templates to figure out which version to use -- as Dirk notes we already provide all the X.Y.Z tags explicitly, so it's not much for a downstream user application to determine that 3.6.3 is the latest 3.6 version and pull the desired image...

**Comment by eddelbuettel** [comment] 2020-05-06 21:37
The aforementioned 'tool' to determine versions that I was thinking of is on CRAN as package [rversions](https://cran.r-project.org/package=rversions).  As Carl says, it is probably more robust to have the selection and preference logic downstream.

**Comment by cboettig** [comment] 2020-09-25 03:00
Duplicate of #349 .  Will revisit once new build system is more finished

**Closed by cboettig** 2020-09-25 03:00 UTC
