### ISSUE TITLE
RStudio-daily tags not updating.

### ISSUE THREAD

**Issue by Thell** [rocker-org/rocker#105] opened 2015-01-24 16:50 UTC
verse @ [ed2a094f](https://index.docker.io/v1/repositories/rocker/rstudio-daily/tags/verse) created on 2015-01-24T08:33:32.794820153Z
master @ [bfdd3494](https://index.docker.io/v1/repositories/rocker/rstudio-daily/tags/master) created on 2015-01-22T20:37:58.455226577Z
latest still @ [8a67427e](https://index.docker.io/v1/repositories/rocker/rstudio-daily/tags/latest) created on 2015-01-20T08:22:17.506267187Z

**Comment by cboettig** [comment] 2015-01-24 18:41
Yup, this appears to be a bug with docker hub.  I've had a support ticket
in since you first mentioned it, they've confirmed the problem but just
asked if rebuilding fixes it, which it doesn't, so I'm still waiting.

**Comment by cboettig** [comment] 2015-02-11 17:28
The tags seem to be updating again, though my support ticket was never notified explicitly that things have changed.  For instance, you should be able to pull now and get last night's build, which conveniently removes that annoying error message on start-up (that I think you brought to my attention, see https://support.rstudio.com/hc/communities/public/questions/202656007-Cryptic-error-on-starting-RStudio-daily-with-R-devel?page=1#answer-204313697)

Anyway, will close this for now. Thanks again for the bug report.

**Closed by cboettig** 2015-02-11 17:28 UTC

**Comment by cboettig** [comment] 2015-03-05 18:18
I've just been informed by Docker support that this bug was confirmed (whereby the tag does not always update) and a fix has just been pushed to production.  Thanks again for the report.

**Comment by eddelbuettel** [comment] 2015-03-05 18:29
:+1: Nice work!
